services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wiparking
      POSTGRES_PASSWORD: wiparking
      POSTGRES_DB: wiparking
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: wiparking@gmail.com
      PGADMIN_DEFAULT_PASSWORD: wiparking
    volumes:
      - ./pgadmin:/var/lib/pgadmin

    networks:
      - postgres
    depends_on:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  data:
  pgadmin:
