services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wibeatz
      POSTGRES_PASSWORD: wibeatz
      POSTGRES_DB: wibeatz
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: wibeatz@wibeatz.com
      PGADMIN_DEFAULT_PASSWORD: wibeatz
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  data:
  pgadmin: